name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
   CI:
    runs-on: [self-hosted, windows, x64]
    steps:
      - run: echo "Obter o código"
      - run: echo "Executar o Docker Build"
      - run: echo "Enviar a Imagem Docker para o Docker"

   CD:
    runs-on: [self-hosted, windows, x64]
    steps:
      - run: echo "Obter o código"
      - run: echo "Configurar o KubeConfig"
      - run: echo "Executar o apply"
    
    
